name: ligo
channels:
  - conda-forge
dependencies:
    - python=3.9 
    - cycler==0.11.0
    - fonttools==4.34.4
    - h5py==3.7.0
    - kiwisolver==1.4.4
    - matplotlib==3.5.2
    - numpy==1.23.1
    - pillow==9.2.0
    - scipy==1.8.1
    - ipython=8.2.0
    - ipython=8.2.0